### ISSUE TITLE
Spark ENTRYPOINT

### ISSUE THREAD

**Issue by ghost** [vishnu2kmohan/spark-dcos-docker#1]
Shouldn't the docker file contain the SPARk ENTRYPOINT and call to run.sh ?

**Comment by vishnu2kmohan** [comment]
@krishdey Closing per our offline conversation.

We don't specify an `ENTRYPOINT` in the official Mesosphere Spark Docker Images either: https://github.com/mesosphere/spark-build/blob/master/docker/Dockerfile#L91

This image is a just a rebase of our official build with Debian 9.3 as the base image with just a few system utils and everything else coming from `conda-forge`

I have already tested this unified image on both CentOS (will pass adequately for RHEL, where the uid for `nobody`=`99`) and CoreOS (where the uid for `nobody`=`65534`) and it works just fine in a `strict` Enterprise DC/OS cluster.
